import { createSlice } from '@reduxjs/toolkit'
export const serviceSlice = createSlice({
    name: 'service',
    //This name is primarily used to prefix the action types generated by RTK for that slice.
    initialState: { 
        openAddPostModel: false,
        openEditProfileModel:false    
    },
    reducers: {
     setOpenAddPostModel:(state,action)=>{
        state.openAddPostModel = action.payload
     },
     setOpenEditProfileModel:(state,action)=>{
        state.openEditProfileModel=action.payload;
     }
    },
})

// Action creators are generated for each case reducer function
export const {setOpenAddPostModel,setOpenEditProfileModel} = serviceSlice.actions
export default serviceSlice.reducer